We're having trouble with the Quartz job scheduling library when the database it
is using scales up or down. In the logs we can see messages like:

----
2019-03-12 06:58:07.733 ERROR 3313 --- [_ClusterManager] o.s.s.quartz.LocalDataSourceJobStore     : ClusterManager: Error managing cluster: Failure updating scheduler state when checking-in: Column 'INSTANCE_NAME' cannot be null

org.quartz.JobPersistenceException: Failure updating scheduler state when checking-in: Column 'INSTANCE_NAME' cannot be null
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.clusterCheckIn(JobStoreSupport.java:3406) ~[quartz-2.2.1.jar:na]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.doCheckin(JobStoreSupport.java:3253) ~[quartz-2.2.1.jar:na]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.manage(JobStoreSupport.java:3858) [quartz-2.2.1.jar:na]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport$ClusterManager.run(JobStoreSupport.java:3895) [quartz-2.2.1.jar:na]
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'INSTANCE_NAME' cannot be null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_191]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_191]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_191]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_191]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.Util.getInstance(Util.java:387) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:934) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:1284) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:785) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5098) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994) ~[mysql-connector-java-5.1.39.jar:5.1.39]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-2.5.1.jar:na]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariCP-2.5.1.jar:na]
        at org.quartz.impl.jdbcjobstore.StdJDBCDelegate.insertSchedulerState(StdJDBCDelegate.java:2948) ~[quartz-2.2.1.jar:na]
        at org.quartz.impl.jdbcjobstore.JobStoreSupport.clusterCheckIn(JobStoreSupport.java:3401) ~[quartz-2.2.1.jar:na]
        ... 3 common frames omitted
----

Our database scales up and down dynamically because it is a MySQL-compatible
Amazon Aurora RDS cluster running in serverless mode. We do not have this
problem if we just use a standard RDS instance.

To run this repro code you will need to provision a database and an EC2 instance
in a VPC. The following instructions are based on a CloudFormation template and
some bash commands tested with AMI amzn2-ami-hvm-2.0.20190228-x86_64-gp2 and an
RDS cluster v5.6.10a (serverless mode, not provisioned).

To create a CloudFormation stack at the CLI you can use the following command.
You should only need to change the KeyName and VpcId parameters.

[source,bash]
----
# on your laptop
aws cloudformation create-stack \
 --region ap-southeast-1 \
 --profile dev \
 --stack-name "minimal-repro-`date +%s`" \
 --tags \
   Key=Environment,Value="snapshot" \
 --parameters \
   ParameterKey=ImageId,ParameterValue="ami-00158b185c8cc09dc" \
   ParameterKey=KeyName,ParameterValue="james" \
   ParameterKey=InstanceType,ParameterValue="m4.large" \
   ParameterKey=NameTag,ParameterValue="minimal_repro" \
   ParameterKey=VpcId,ParameterValue="vpc-5be85430" \
  --template-body file://minimal_repro_cloudformation_template.json
----

After the database cluster becomes available and the instance boots up...

[source,bash]
----
# install deps on the EC2 instance
yum install -y git java maven mysql

# check out code
cd /opt && git clone https://github.com/jamesdavidson/quartz-scheduler-exception-repro

# set environment variable parameters
source <(curl -s http://169.254.169.254/latest/user-data)

# sanity check
echo SELECT 1 | mysql -u $MYSQL_USERNAME -p$MYSQL_PASSWORD -h $MYSQL_HOSTNAME $MYSQL_DATABASE

# create the QRTZ_* database tables
cat /opt/quartz-scheduler-exception-repro/setup/qrtz.sql | mysql -u $MYSQL_USERNAME -p$MYSQL_PASSWORD -h $MYSQL_HOSTNAME $MYSQL_DATABASE

# run the mini application
cd /opt/quartz-scheduler-exception-repro/complete && mvn spring-boot:run
----

Once the application is up and running, log in to the AWS Management Console and
choose the RDS service, find the database cluster, open the 'Actions' menu,
click 'Set Capacity' and change from two to four units of capacity. After one or
two minutes you should see some exceptions appear in the console output of the
Spring Boot mini-application.
